config/routes.rb
NinetyNineCats::Application.routes.draw do
  resources :cats do
    member do
      get 'request_rental'
    end
  end
  
  resources :cat_rental_requests do
    member do
      get 'approve'
      get 'deny'
    end
  end
  
  resources :users, only: [:new, :create]
  
  resources :sessions, only: [:new, :create, :destroy, :index]
  
end

app/models/cat_rental_request.rb
class CatRentalRequest < ActiveRecord::Base
  validates :cat_id, :start_date, :end_date, :status, :user_id, presence: true
  validates :status, inclusion: { in: ['PENDING', 'APPROVED', 'DENIED'] }
  validate :no_other_rentals_approved_in_range
  
  after_initialize :set_status_to_pending
  
  belongs_to(
    :cat,
    class_name: 'Cat',
    foreign_key: :cat_id,
    primary_key: :id
  )
  
  has_one(
    :cat_owner,
    through: :cat,
    source: :owner
  )
  
  belongs_to(
    :user,
    class_name: 'User',
    foreign_key: :user_id,
    primary_key: :id
  )
  
  def approve!
    self.class.transaction do
      self.status = 'APPROVED'
      self.save!
      overlapping_pending_requests.update_all(status: 'DENIED')
    end
  end
  
  def deny!
    self.status = 'DENIED'
    self.save!
  end
  
  def pending?
    self.status == "PENDING"
  end
  
  private
  
  def set_status_to_pending
    self.status ||= 'PENDING'
  end
  
  def no_other_rentals_approved_in_range
    unless overlapping_approved_requests.empty?
      errors[:start_date] << "Rental is already approved for this date range"
    end
  end
  
  def overlapping_requests
    range_where = 
    '(? < end_date) AND (? > start_date)'
    
    self.class
      .where(cat_id: self.cat_id)
      .where.not(id: self.id)
      .where(
       range_where,
        start_date,
        end_date
      )
  end
  
  def overlapping_approved_requests
    overlapping_requests.where(status: 'APPROVED')
  end
  
  def overlapping_pending_requests
    overlapping_requests.where(status: 'PENDING')
  end
end

app/controllers/cat_rental_requests_controller.rb
class CatRentalRequestsController < ApplicationController
  before_action :prevent_unauthorized_approval, only: [:approve, :deny]
  
  def new
    @cats = Cat.all
    render :new
  end
  
  def create
    @request = CatRentalRequest.new(req_params)
    
    @request.save
    
    redirect_to cat_url(@request.cat)
  end
  
  def approve
    current_request.approve!
    
    redirect_to cat_url(current_request.cat)
  end
  
  def deny
    current_request.deny!
    
    redirect_to cat_url(current_request.cat)
  end
  
  private
  
  def current_request
    @request ||= CatRentalRequest.find(params[:id])
  end
  
  def prevent_unauthorized_approval
    if current_request.cat_owner != current_user
      redirect_to cat_url(current_request.cat.id) 
    end
  end
  
  def req_params
    req_params = params.require(:rental_request).permit(:cat_id, :start_date, :end_date)
    req_params[:user_id] = current_user.id
    req_params
  end
end

app/helpers/cat_rental_requests_helper.rb
module CatRentalRequestsHelper
end

app/views/cat_rental_requests/_new.html.erb
<form action="<%= cat_rental_requests_url %>" method="POST" id="request-form">
  <h4>Request <%= request.cat.name %></h4>
  
  <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>">
      
  <!-- <label for="cat_id">Choose a Cat</label>
  <br> -->
  <!-- <select name="rental_request[cat_id]" id="cat_id">
    <option value="" />
    <%# @cats.each do |cat| %>
      <option value="<%#= cat.id %>"><%#= cat.name %></option>
    <%# end %>
  </select> -->
  <!-- <br><br> -->
  <input type="hidden" name="rental_request[cat_id]" 
    value="<%= request.cat_id %>">
  <label for="start_date">Start Date</label>
  <br>
  <input type="date" name="rental_request[start_date]" id="start_date">  
  <br><br>
  <label for="end_date">End Date</label>
  <br>
  <input type="date" name="rental_request[end_date]" id="end_date">
  <br>
  <br>
  <input type="submit" value="Submit Request">
  
</form>