config/routes.rb
NinetyNineCats::Application.routes.draw do
  resources :cats do
    member do
      get 'request_rental'
    end
  end
  
  resources :cat_rental_requests do
    member do
      get 'approve'
      get 'deny'
    end
  end
  
  resources :users, only: [:new, :create]
  
  resources :sessions, only: [:new, :create, :destroy, :index]
  
end

app/models/cat.rb
class Cat < ActiveRecord::Base
  COLORS = ['Black', 'White', 'Brown', 'Grey', 'Orange']
  
  validates :age, numericality: true
  validates :color, inclusion: {
    in: COLORS
  }  
  validates :sex, inclusion: {
    in: ['M', 'F']
  }
  validates :age, :birth_date, :color, :name, :sex, :description, presence: true

  has_many(
    :rental_requests,
    class_name: "CatRentalRequest",
    foreign_key: :cat_id,
    primary_key: :id,
    dependent: :destroy
  )
  
  belongs_to(
    :owner,
    class_name: "User",
    foreign_key: :user_id,
    primary_key: :id
  )
  
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  before_action :prevent_unauthorized_updates, only: [:edit, :update, :destroy]
  
  def index
    @cats = Cat.all.order(:name)
    render :index
  end
  #
  # def request_rental
  #   @cat = Cat.find(params[:id])
  #   @request = CatRentalRequest.new(cat_id: @cat.id)
  #
  #   redirect_to cat_url(@cat)
  # end
  
  def show
    @request = CatRentalRequest.new(cat_id: current_cat.id)
    @requests = current_cat.rental_requests.order(:start_date)
    @display_attrs = current_cat.attributes.except(
      "id", "created_at", "updated_at", "name", "description"
    )
    render :show
  end
  
  def new
    @cat = Cat.new
    render :new
  end
  
  def edit
    current_cat
    render :edit
  end
  
  def create
    @cat = Cat.new(cat_params)
    
    if @cat.save
      redirect_to cat_url(@cat)
    else
      render :new
    end
  end
  
  def update    
    if current_cat.update(cat_params)
      redirect_to cat_url(current_cat)
    else
      render :update
    end
  end
  
  private
  
  def current_cat
    @cat ||= Cat.find(params[:id])
  end
  
  def cat_params
    cat_params = params.require(:cat).permit(
      :name, :age, :sex, :color, :birth_date, :description
    )
    
    cat_params[:user_id] = current_user.id
    cat_params
  end
  
  def prevent_unauthorized_updates
    redirect_to cats_url if current_cat.owner != current_user
  end
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/views/cats/_form.html.erb
<form action="<%= cat.persisted? ? cat_url(cat) : cats_url %>" method="POST">
    <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>">
    
  <% if cat.persisted? %>
  <input type="hidden" name="_method" value="PATCH">
  <% end %>
  
  <label for="cat_name">Name</label>
  <br>
  <input type="text" name="cat[name]" id="cat_name" value="<%= cat.name %>">
  
  <br>
  
  <label for="cat_age">Age</label>
  <br>
  <input type="text" name="cat[age]" id="cat_age" value="<%= cat.age %>">
  
  <br><br>
  
  <input type="radio" name="cat[sex]" id="cat_sex_female" value="F" 
   <%= "checked" if cat.sex == "F" %> >
  <label for="cat_sex_female">Female</label>
  <br>
  <input type="radio" name="cat[sex]" id="cat_sex_male" value="M"
    <%= "checked" if cat.sex == "M" %> >
  <label for="cat_sex_male">Male</label>
  
  <br><br>
  
  <label for="cat_color">Color</label>
  <br>
  <select name="cat[color]" id="cat_color">
  <option value="" />
  <% Cat::COLORS.each do |color| %>
    <option value="<%= color %>" <%="selected" if cat.color == color %>>
      <%= color %></option>
  <% end %>
  </select>
  
  <br><br>
  
  <label for="cat_birth_date">Birth Date</label>
  <br>
  <input type="date" name="cat[birth_date]" id="cat_birth_date" value="<%= cat.birth_date %>">
  
  <br><br>
  
  <label for="cat_description">Description</label>
  <br>
  <textarea name="cat[description]" id="cat_description"><%= cat.description %></textarea>
  <br>
  <input type="submit" value="Save cat">
</form>

app/views/cats/edit.html.erb
<%= render partial: "form", locals: { cat: @cat } %>

app/views/cats/index.html.erb
<h2>Cat Rentals</h2>

<ul>
  <% @cats.each do |cat| %>
  <li><%= link_to cat.name, cat_url(cat) %></li>
  <% end %>
</ul>

app/views/cats/new.html.erb
<%= render partial: "form", locals: { cat: @cat } %>

app/views/cats/show.html.erb
<div class="cat-info">
  <div class="image">
    <img src="http://placekitten.com/300/300" />
  </div>
  
  <h2><%= @cat.name %></h2>

  <div id="cats">
    <% @display_attrs.each do |name, value| %>
    <div class="attribute">
      <div class="name"><%= name.humanize %></div>
      <div class="value"><%= value %></div>
    </div>
    <% end %>
    <div class="attribute">
      <div class="name">Description</div>
      <div class="value"><%= @cat.description %></div>
    </div>
  </div>
</div>

<br>

<div class="req-info">
  <h3>Rental Requests</h3>
  <%= render partial: "cat_rental_requests/new", locals: { request: @request } %>
  <div id="requests">
    <div class="header">Requester</div>
    <div class="header">Start Date</div>
    <div class="header">End Date</div>
    <div class="header">Status</div>
    
    <% if @requests.any? { |r| r.pending? && r.cat_owner == current_user } %>
    <div class="header">Approve</div>  
    <% end %> 
    
  
    <% @requests.each do |req| %>    
      <div class="request">
        <div class="user">
          <%= req.user.user_name %>
        </div>
        
        <div class="date"><%= req.start_date %></div>
        <div class="date"><%= req.end_date %></div>
        <div class="status"><%= req.status.capitalize %></div>
      
        <% if req.pending? && current_user == req.cat_owner %>
        <div class="approval">
          <%= link_to "Approve", approve_cat_rental_request_url(req) %> / 
          <%= link_to "Deny", deny_cat_rental_request_url(req) %>
        </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>